pipeline:
  build:
    image: quay.io/ukhomeofficedigital/scala-sbt-nodejs
    commands:
      - /root/entrypoint.sh
      - sbt +publish
    environment:
      - ARTIFACTORY_USERNAME=drt_artifactory
    secrets:
      - ARTIFACTORY_PASSWORD
    when:
      event:
        - push
      branch:
        - ${DRONE_BRANCH}
